[package]
name = "webpad"
version = "1.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
tungstenite = "0.24.0"
winapi = { version = "0.3", features = ["winuser"] }
include_dir = "0.7.4"
mime_guess = "2.0.5"
local-ip-address = "0.6.3"
qrcode = "0.14.1"