[package]
name = "webpad"
version = "2.0.0"
edition = "2021"

[dependencies]
enigo = "0.3.0"
tungstenite = "0.24.0"
local-ip-address = "0.6.3"
tiny_http = "0.12"
include_dir = "0.7.3"
mime_guess = "2.0.4"
qrcode = "0.14.1"
